name: Format and test

on:
    push:
        branches: ['*']
    pull_request:
        branches: ['main']

jobs:
    build:
        runs-on: 'ubuntu-latest'
        strategy:
            fail-fast: false
            matrix:
                python-version: ['3.12']

        steps:
            - uses: actions/checkout@v4

            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Setup uv
              run: |
                curl -LsSf https://astral.sh/uv/install.sh | sh
                uv venv
            - name: Install dependencies
              run: |
                  source .venv/bin/activate
                  uv pip install --upgrade pip
                  uv pip install -r requirements.txt
                  uv pip install -r requires-dev.txt
            - name: Run unit tests
              run: |
                source .venv/bin/activate
                python -m pytest tests/
